/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualisasiDataRouteImport } from './routes/visualisasiData'
import { Route as DaftarImpianRouteImport } from './routes/daftarImpian'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DaftarImpianWishlistIdRouteImport } from './routes/daftarImpian.$wishlistId'

const VisualisasiDataRoute = VisualisasiDataRouteImport.update({
  id: '/visualisasiData',
  path: '/visualisasiData',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarImpianRoute = DaftarImpianRouteImport.update({
  id: '/daftarImpian',
  path: '/daftarImpian',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarImpianWishlistIdRoute = DaftarImpianWishlistIdRouteImport.update({
  id: '/$wishlistId',
  path: '/$wishlistId',
  getParentRoute: () => DaftarImpianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftarImpian': typeof DaftarImpianRouteWithChildren
  '/visualisasiData': typeof VisualisasiDataRoute
  '/daftarImpian/$wishlistId': typeof DaftarImpianWishlistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftarImpian': typeof DaftarImpianRouteWithChildren
  '/visualisasiData': typeof VisualisasiDataRoute
  '/daftarImpian/$wishlistId': typeof DaftarImpianWishlistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftarImpian': typeof DaftarImpianRouteWithChildren
  '/visualisasiData': typeof VisualisasiDataRoute
  '/daftarImpian/$wishlistId': typeof DaftarImpianWishlistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftarImpian'
    | '/visualisasiData'
    | '/daftarImpian/$wishlistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daftarImpian' | '/visualisasiData' | '/daftarImpian/$wishlistId'
  id:
    | '__root__'
    | '/'
    | '/daftarImpian'
    | '/visualisasiData'
    | '/daftarImpian/$wishlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarImpianRoute: typeof DaftarImpianRouteWithChildren
  VisualisasiDataRoute: typeof VisualisasiDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualisasiData': {
      id: '/visualisasiData'
      path: '/visualisasiData'
      fullPath: '/visualisasiData'
      preLoaderRoute: typeof VisualisasiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftarImpian': {
      id: '/daftarImpian'
      path: '/daftarImpian'
      fullPath: '/daftarImpian'
      preLoaderRoute: typeof DaftarImpianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftarImpian/$wishlistId': {
      id: '/daftarImpian/$wishlistId'
      path: '/$wishlistId'
      fullPath: '/daftarImpian/$wishlistId'
      preLoaderRoute: typeof DaftarImpianWishlistIdRouteImport
      parentRoute: typeof DaftarImpianRoute
    }
  }
}

interface DaftarImpianRouteChildren {
  DaftarImpianWishlistIdRoute: typeof DaftarImpianWishlistIdRoute
}

const DaftarImpianRouteChildren: DaftarImpianRouteChildren = {
  DaftarImpianWishlistIdRoute: DaftarImpianWishlistIdRoute,
}

const DaftarImpianRouteWithChildren = DaftarImpianRoute._addFileChildren(
  DaftarImpianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarImpianRoute: DaftarImpianRouteWithChildren,
  VisualisasiDataRoute: VisualisasiDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
